groups:
  - name: backend_app_alert
    rules:
      - alert: HighRequestRate
        expr: rate(http_requests_total[1m]) > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High request rate detected"
          description: "Request rate has exceeded 5 requests per second for the past minute."

  - name: service_availability_alerts
    rules:
      - alert: GoServiceDown
        expr: up{job="backend_app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Backend services is down"
          description: "The Backend App service has been unreachable for more than 1 minute."
      - alert: BackendHighCPU
        expr: (1 - avg by(instance) (rate(node_cpu_seconds_total{job="node-exporter",mode="idle"}[5m]))) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Backend CPU usage is high"
          description: "The CPU usage on the Backend server instance {{ $labels.instance }} is over 80% for the last 5 minutes."