[server]
app_name="Toko Online"
mode = "debug"
port = "9000"
http_timeout = 60
cache_expired = 24
cache_purged = 60

[database]
db_driver = "mysql"
db_host = "localhost"
db_port = "3306"
db_name = "toko_online"
db_username = "user"
db_password = "password"

[pool]
conn_idle = 10
conn_max = 20
conn_lifetime = 60

[jwt]
day_expired = 60
signature_key = "SuperShy!"

[message_broker]
rabbimq_url="amqp://guest:guest@localhost:5672/"

[cache]
cache_addr = "localhost:6379"
cache_password = ""

[payment]
mode="sandbox"
sb_server_key="SB-Mid-server-FxnHTffLCcsFPQjMcJTcJrTb"

[smtp]
host="smtp.mailersend.net"
port=587
username="MS_BiRD7P@trial-351ndgw215rgzqx8.mlsender.net"
password="YLkGFhT4XKhPExD7"