global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job']

  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  
  receiver: 'discord-alerts'

receivers:
  - name: 'discord-alerts'
    webhook_configs:
      - url: 'https://discord.com/api/webhooks/1294609149870608454/qulfJf6thrWO7nMwSBFG53aTgTzuuuy-aqB75w4L4KCXDAT5mmLsvHF0t_q9U5qbAh2L'
        send_resolved: true