groups:
  - name: test_alert_group
    rules:
      - alert: TestAlert
        expr: vector(1)  # This triggers the alert instantly
        for: 1m
        labels:
          severity: test
        annotations:
          summary: "This is a test alert"
          description: "Testing the Alertmanager-Discord integration"
        # Go routines gt 10
      - alert: goRoutinesGt10
        expr: avg(go_goroutines) > 10
        for: 1m
        labels:
          severity: page
        annotations:
          summary: "Go Routines AVG grater than 10"

      # Go routines gt 100000
      - alert: goRoutinesGt100000
        expr: avg(go_goroutines) > 100000
        for: 1m
        labels:
          severity: page
        annotations:
          summary: "Go Routines AVG grater than 100000"

  - name: backend_app_alert
    rules:
      - alert: HighRequestRate
        expr: rate(http_requests_total[1m]) > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High request rate detected"
          description: "Request rate has exceeded 5 requests per second for the past minute."
      - alert: HighCPUUsage
        expr: (100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% for more than 5 minutes."
      - alert: BackendHighCPU
        expr: (1 - avg by(instance) (rate(node_cpu_seconds_total{job="node-exporter",mode="idle"}[5m]))) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Backend CPU usage is high"
          description: "The CPU usage on the Backend server instance {{ $labels.instance }} is over 80% for the last 5 minutes."

  - name: service_availability_alerts
    rules:
      - alert: GoServiceDown
        expr: up{job="backend_app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Backend services is down"
          description: "The Backend server backend has been unreachable for more than 1 minute."
          
      