global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alerting_rules.yml'

# Grafana URL: http://cortex:9009/api/prom
remote_write:
  - url: http://cortex:9009/api/prom/push

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'backend_app'
    static_configs:
      - targets: ['backend_app:9000']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']